name: Build test
on:
  push:
    branches:
      - master
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: bash ci.sh deps
    - name: Build LLVM
      run: bash ci.sh llvm
    - uses: actions/upload-artifact@v2
      with:
       name: Upload stage1 TCT
       path: /home/runner/work/tc-build/tc-build/install
